### ISSUE TITLE
Alice_Article_HybridVigourLab

### ISSUE THREAD

**Issue by derele** [derele/Eimeria_Lab#6]
This can be deleted, right @alicebalard ?

**Comment by alicebalard** [comment]
Hell yes. Everything I need was backed up and cleaned in the repo for my article 2. The rest here is remaining of previous coding, that you can easily get rid of.

**Comment by derele** [comment]
Okay @lubomirBednar please delete this folder.

**Comment by LubomirBednar** [comment]
Deleted, along with most other code
