### ISSUE TITLE
Broken Script: Exp008.R

### ISSUE THREAD

**Issue by derele** [derele/Eimeria_Lab#9]
This script is broken: 
https://github.com/derele/Eimeria_Lab/blob/master/R/Exp008.R

`source("functions4InfectionExperiments.R")`

The sourced script does not exist anywhere. 

Please fix it @LubomirBednar ? Are these functions still used? What is the script used for?

**Comment by LubomirBednar** [comment]
This is a leftover script from a passaging. The source script was probably hard coded.
Not The functions live on in https://github.com/derele/Eimeria_Lab/tree/master/R 
Deleting it and closing this issue.
